---
title: "My First Blog"
author: "Ravi Duvvuri"
date: "May 1, 2019"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

## Spring 2019: DSBA5122 (May 1st 2019)

Visual Analytics is my first course in the DSBA program. The course website was built by Andrew Heiss and the content is managed by Prof.Ryan. Course schedule is very well laid out and it was upto date with the Readings, Assignments and Class material. Datacamp courses are designed in such a way that even a student with no background of R can follow these courses and get upto speed. Problem set's were challenging and fun, Random Quizzes tested us on the lectures and Design contest is when I had an opportunity to know and work with other students and it was an amazing experience. We did great with our presentation. 

I would say, overall I am very happy with the course content and my performance given that I am going back to school after 10 plus years.

I should mention that I am a decent R programmer now with exposure to Shiny and basics of Machine learning.







